name: Default Deployment Pipeline

# This workflow should run everytime a pull request is created or updated
# and has branches 'main' or 'develop' as the target.

# JOBS:
# [x] code linting
# [ ] runs unit tests
# [ ] ...

on:
  pull_request:
    branches:
      ['main', 'develop']
  push:
    branches:
      ['main', 'develop']

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    permissions:
      checks: write
      contents: write
      pull_request: write

    steps:
      # Creates an instance from our branch into Github's virtual machine
      - name: Checkout
        uses: actions/checkout@v4

      # Installs and sets up a Node version into Github's virtual machine 
      - name: Installing Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installing yarn
        run: npm install --global yarn

      - name: Installing dependencies
        run: yarn install

      - name: Linting
        uses: wearerequired/lint-action@v2
        with:
          github_token: ${{ secrets.github_token }}
          auto_fix: ${{ github.event_name == 'pull_request' }}
          prettier: true

      - name: Build
        run: yarn build

      - name: Testing
        run: yarn test:all